export type Member = {
  id: string;
  name: string;
  country: string;
  university: string;
  area: string;
  role: string;
  slug: string;
  image: string | null;
  video?: string;
  linkedIn: string | null;
  featured?: boolean;
};

export const members: Member[] = [
  {
    "id": "CLH-076",
    "name": "Alberto Sánchez Prieto",
    "country": "España",
    "university": "Universidad de Córdoba",
    "area": "Veterinaria",
    "role": "Cofundador",
    "slug": "alberto-sanchez-prieto",
    "image": "/images/members/alberto-sanchez-prieto.webp",
    "video": "/videos/alberto-sanchez-prieto.mp4",
    "linkedIn": "https://www.linkedin.com/in/albertosprietocolmenero/",
    "featured": false
  },
  {
    "id": "CLH-075",
    "name": "Jorge Gregorio Garcia-Heras",
    "country": "España",
    "university": "CUNEF Universidad",
    "area": "Finanzas",
    "role": "Cofundador",
    "slug": "jorge-gregorio-garcia-heras",
    "image": "/images/members/jorge-gregorio-garcia-heras.jpg",
    "video": "/videos/jorge-gregorio-garcia-heras.mp4",
    "linkedIn": "https://www.linkedin.com/in/jgreego/",
    "featured": true
  },
  {
    "id": "CLH-005",
    "name": "Camila Calvo",
    "country": "Panamá",
    "university": "ADEN",
    "area": "Marketing",
    "role": "Líder de Marketing",
    "slug": "camila-calvo",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/camila-calvo-de-la-guardia/",
    "featured": false
  },
  {
    "id": "CLH-008",
    "name": "Cristóbal Vargas Marchant",
    "country": "Chile",
    "university": "Universidad de Chile",
    "area": "Economía",
    "role": "Líder Finanzas",
    "slug": "cristobal-vargas-marchant",
    "image": "/images/members/cristobal-vargas-marchant.webp",
    "video": "/videos/cristobal-vargas-marchant.mp4",
    "linkedIn": "https://www.linkedin.com/in/crist%C3%B3bal-vargas-marchant-4289151b5/",
    "featured": false
  },
  {
    "id": "CLH-028",
    "name": "Emily Torres Pineda",
    "country": "Colombia",
    "university": "Universidad del Rosario",
    "area": "Derecho",
    "role": "Líder Jurídico y Relaciones Internacionales",
    "slug": "emily-torres-pineda",
    "image": "/images/members/emily-torres-pineda.webp",
    "linkedIn": "https://www.linkedin.com/in/emily-torres-pineda/",
    "featured": false
  },
  {
    "id": "CLH-041",
    "name": "Federico Matz",
    "country": "Argentina",
    "university": "Universidad de San Andrés",
    "area": "Negocios Digitales",
    "role": "Líder Comunidad y Talento",
    "slug": "federico-matz",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/federico-matz/",
    "featured": false
  },
  {
    "id": "CLH-025",
    "name": "Michelle Rogel",
    "country": "México",
    "university": "Anahuac Mayab",
    "area": "Ingeniería Mecatrónica",
    "role": "Líder Eventos y Experiencias",
    "slug": "michelle-rogel",
    "image": "/images/members/michelle-rogel.webp",
    "video": "/videos/michelle-rogel.mp4",
    "linkedIn": "https://www.linkedin.com/in/michelle-rogel-garc%C3%ADa-a37820219/",
    "featured": false
  },
  {
    "id": "CLH-011",
    "name": "Renata Ana Emilia Berho",
    "country": "Argentina",
    "university": "Universidad Nacional de la Plata",
    "area": "Ingeniería Aeroespacial",
    "role": "Líder Tecnología",
    "slug": "renata-berho",
    "image": "/images/members/renata-berho.webp",
    "video": "/videos/renata-berho.mp4",
    "linkedIn": "https://www.linkedin.com/in/renata-berho-02264230a/",
    "featured": false
  },
  {
    "id": "CLH-034",
    "name": "Santiago Nariño Rivera",
    "country": "Colombia",
    "university": "Universidad del Rosario",
    "area": "Negocios Internacionales y Finanzas",
    "role": "Líder Operaciones y Eficiencia",
    "slug": "santiago-narino-rivera",
    "image": "/images/members/santiago-narino-rivera.webp",
    "video": "/videos/santiago-narino-rivera.mp4",
    "linkedIn": "https://www.linkedin.com/in/santiago-nari%C3%B1o-rivera-10351429b/",
    "featured": false
  },
  {
    "id": "CLH-001",
    "name": "Adrian Alava",
    "country": "Ecuador",
    "university": "UEES",
    "area": "Negocios Internacionales",
    "role": "Operaciones y Eficiencia",
    "slug": "adrian-alava",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/adrian-alava-93a64b312/",
    "featured": false
  },
  {
    "id": "CLH-053",
    "name": "Alexa Ramirez Garcia",
    "country": "México",
    "university": "Tec. De Monterrey",
    "area": "Marketing",
    "role": "Marketing",
    "slug": "alexa-ramirez-garcia",
    "image": "/images/members/alexa-ramirez-garcia.webp",
    "linkedIn": "https://www.linkedin.com/in/alexaramirezg/",
    "featured": false,
    "video": "/videos/alexa-ramirez-garcia.mp4"
  },
  {
    "id": "CLH-004",
    "name": "Byron Zambrano",
    "country": "Ecuador",
    "university": "UEES",
    "area": "Relaciones Internacionales | Eventos y Experiencias",
    "role": "Relaciones Internacionales | Eventos y Experiencias",
    "slug": "byron-zambrano",
    "image": "/images/members/byron-zambrano.webp",
    "video": "/videos/byron-zambrano.mp4",
    "linkedIn": "https://www.linkedin.com/in/byron-zambrano-47853230b/",
    "featured": false
  },
  {
    "id": "CLH-006",
    "name": "Christopher Marroquin",
    "country": "El Salvador",
    "university": "ESEN",
    "area": "Ingeniería de Software",
    "role": "BEWAY Tecnología",
    "slug": "christopher-marroquin",
    "image": "/images/members/christopher-marroquin.webp",
    "video": "/videos/christopher-marroquin.mp4",
    "linkedIn": "https://www.linkedin.com/in/christopher-marroquin23/?locale=es",
    "featured": false
  },
  {
    "id": "CLH-043",
    "name": "Claudio Federico Buffardi Witzke",
    "country": "México",
    "university": "Anáhuac México Norte",
    "area": "Ingeniería Industrial",
    "role": "Operaciones y Eficiencia",
    "slug": "claudio-federico-buffardi-witzke",
    "image": "/images/members/claudio-federico-buffardi-witzke.webp",
    "video": "/videos/claudio-federico-buffardi-witzke.mp4",
    "linkedIn": "https://www.linkedin.com/in/claudio-buffardi/",
    "featured": false
  },
  {
    "id": "CLH-009",
    "name": "Daniel Eli Lopez",
    "country": "El Salvador",
    "university": "Universidad Francisco Gavidia",
    "area": "Negocios e innovación",
    "role": "Tecnología | Eventos y Experiencias",
    "slug": "daniel-lopez",
    "image": "/images/members/daniel-lopez.webp",
    "video": "/videos/daniel-lopez.mp4",
    "linkedIn": "https://www.linkedin.com/in/daniellopezdev/",
    "featured": false
  },
  {
    "id": "CLH-010",
    "name": "Daniela Olmedo",
    "country": "Chile",
    "university": "Universidad de Chile",
    "area": "Finanzas",
    "role": "Finanzas",
    "slug": "daniela-olmedo",
    "image": "/images/members/daniela-olmedo.webp",
    "video": "/videos/daniela-olmedo.mp4",
    "linkedIn": "https://www.linkedin.com/in/daniela-olmedo-13a029318/",
    "featured": false
  },
  {
    "id": "CLH-013",
    "name": "Fabian Rivera",
    "country": "Panamá",
    "university": "USMA",
    "area": "Ingenieria Industrial",
    "role": "Comunidad y Talento",
    "slug": "fabian-rivera",
    "image": "/images/members/fabian-rivera.webp",
    "linkedIn": "https://www.linkedin.com/in/fabian-rivera-342ab8366/",
    "featured": false
  },
  {
    "id": "CLH-016",
    "name": "Felipe Hernández Marín",
    "country": "España",
    "university": "Universidad CEU San Pablo",
    "area": "Ciencias de la salud",
    "role": "Relaciones Internacionales | Eventos y Experiencias",
    "slug": "felipe-hernandez-marin",
    "image": "/images/members/felipe-hernandez-marin.webp",
    "video": "/videos/felipe-hernandez-marin.mp4",
    "linkedIn": "https://www.linkedin.com/in/felipe-hernandez-marin/",
    "featured": false
  },
  {
    "id": "CLH-017",
    "name": "Fernando Fuentes",
    "country": "El Salvador",
    "university": "ESEN",
    "area": "Ingeniería de Software",
    "role": "BEWAY Tecnología",
    "slug": "fernando-fuentes",
    "image": "/images/members/fernando-fuentes.webp",
    "video": "/videos/fernando-fuentes.mp4",
    "linkedIn": "https://www.linkedin.com/in/fernando-fuentes-aba154259/?locale=es",
    "featured": false
  },
  {
    "id": "CLH-020",
    "name": "Gabriela Gallardo",
    "country": "Ecuador",
    "university": "UEES",
    "area": "Business",
    "role": "Comunidad y Talento",
    "slug": "gabriela-gallardo",
    "image": "/images/members/gabriela-gallardo.webp",
    "linkedIn": "https://www.linkedin.com/in/gabriela-gallardo-96a7842a5/",
    "featured": false,
    "video": "/videos/gabriela-gallardo.mp4"
  },
  {
    "id": "CLH-067",
    "name": "Germán Benito Menéndez",
    "country": "España",
    "university": "ISDIN",
    "area": "Farmacia y Cosmética",
    "role": "Expansión Internacional",
    "slug": "german-benito-menendez",
    "image": "/images/members/german-benito-menendez.webp",
    "video": "/videos/german-benito-menendez.mp4",
    "linkedIn": "https://www.linkedin.com/in/germanbenito21/",
    "featured": false
  },
  {
    "id": "CLH-022",
    "name": "Ian Anthony Ruiz Rivas",
    "country": "Ecuador",
    "university": "UEES",
    "area": "Negocios Internacionales",
    "role": "Relaciones Internacionales | Eventos y Experiencias",
    "slug": "ian-ruiz",
    "image": "/images/members/ian-ruiz.webp",
    "video": "/videos/ian-ruiz.mp4",
    "linkedIn": "https://www.linkedin.com/in/ian-ruiz/?locale=es",
    "featured": false
  },
  {
    "id": "CLH-002",
    "name": "José Humberto León Ledesma",
    "country": "México",
    "university": "Universidad Anáhuac Mayab",
    "area": "Entretenimiento/Diversidad e Inclusión",
    "role": "Eventos y Experiencias",
    "slug": "jose-humberto-leon-ledesma",
    "image": "/images/members/jose-humberto-leon-ledesma.webp",
    "video": "/videos/jose-humberto-leon-ledesma.mp4",
    "linkedIn": "https://www.linkedin.com/in/humberto-le%C3%B3n-ledesma-1bb4111b7/",
    "featured": false
  },
  {
    "id": "CLH-018",
    "name": "Josue Roberto Polanco",
    "country": "El Salvador",
    "university": "ESEN",
    "area": "Tecnología",
    "role": "BEWAY Tecnología",
    "slug": "josue-roberto-polanco",
    "image": "/images/members/josue-roberto-polanco.webp",
    "linkedIn": "https://www.linkedin.com/in/roberto-polanco-0bb176354/",
    "featured": false,
    "video": "/videos/josue-roberto-polanco.mp4"
  },
  {
    "id": "CLH-055",
    "name": "Juan Sebastián Gomez Vera",
    "country": "Colombia",
    "university": "Universidad Pontificia Bolivariana",
    "area": "Teconología",
    "role": "Tecnología",
    "slug": "juan-sebastian-gomez-vera",
    "image": "/images/members/juan-sebastian-gomez-vera.webp",
    "video": "/videos/juan-sebastian-gomez-vera.mp4",
    "linkedIn": "https://www.linkedin.com/in/juansgomezv/",
    "featured": false
  },
  {
    "id": "CLH-026",
    "name": "Kevin Elias Luna Palacios",
    "country": "El Salvador",
    "university": "ESEN",
    "area": "Ciberseguridad y Desarrollo",
    "role": "BEWAY Tecnología",
    "slug": "kevin-elias-luna-palacios",
    "image": "/images/members/kevin-elias-luna-palacios.webp",
    "video": "/videos/kevin-elias-luna-palacios.mp4",
    "linkedIn": "https://www.linkedin.com/in/kevin-luna-a0b024325/?locale=es",
    "featured": false
  },
  {
    "id": "CLH-029",
    "name": "Krissia Alejandra Bueno Viana",
    "country": "El Salvador",
    "university": "ESEN",
    "area": "Business",
    "role": "Marketing",
    "slug": "krissia-alejandra-bueno",
    "image": "/images/members/krissia-alejandra-bueno.webp",
    "video": "/videos/krissia-alejandra-bueno.mp4",
    "linkedIn": "https://www.linkedin.com/in/krissia-bueno-a61a4031a/",
    "featured": false
  },
  {
    "id": "CLH-007",
    "name": "Larissa Arias Alamilla",
    "country": "México",
    "university": "Anahuac Mayab",
    "area": "Operaciones y eficiencia / Eventos y experiencias",
    "role": "Operaciones y Eficiencia | Eventos y Experiencias",
    "slug": "larissa-arias-alamilla",
    "image": "/images/members/larissa-arias-alamilla.webp",
    "video": "/videos/larissa-arias-alamilla.mp4",
    "linkedIn": "https://www.linkedin.com/in/larissa-arias-alamilla-7a3931374/",
    "featured": false
  },
  {
    "id": "CLH-068",
    "name": "Leonardo Lozano",
    "country": "Ecuador",
    "university": "Universidad San Francisco de Quito",
    "area": "Economía",
    "role": "Tecnología",
    "slug": "leonardo-lozano",
    "image": "/images/members/leonardo-lozano.webp",
    "video": "/videos/leonardo-lozano.mp4",
    "linkedIn": "https://www.linkedin.com/in/leonardo-lozano-8a8710371/?locale=en",
    "featured": false
  },
  {
    "id": "CLH-040",
    "name": "Lucía Maria Vizcarrondo",
    "country": "Puerto Rico",
    "university": "Universidad de Navarra",
    "area": "Marketing",
    "role": "Eventos y Experiencias",
    "slug": "lucia-maria-vizcarrondo",
    "image": "/images/members/lucia-maria-vizcarrondo.webp",
    "video": "/videos/lucia-maria-vizcarrondo.mp4",
    "linkedIn": "https://www.linkedin.com/in/luc%C3%ADa-maria-vizcarrondo-0928613ab/",
    "featured": false
  },
  {
    "id": "CLH-032",
    "name": "Manuel Losa",
    "country": "España",
    "university": "Universidad Politecnica de Madrid",
    "area": "Ingenieria Aeroespacial",
    "role": "BEWAY Tecnología",
    "slug": "manuel-losa",
    "image": "/images/members/manuel-losa.webp",
    "video": "/videos/manuel-losa.mp4",
    "linkedIn": "https://www.linkedin.com/in/manuel-losa-l%C3%B3pez-7560913aa/",
    "featured": false
  },
  {
    "id": "CLH-033",
    "name": "María Amo",
    "country": "España",
    "university": "URJC",
    "area": "Marketing",
    "role": "Eventos y Experiencias",
    "slug": "maria-amo",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/mar%C3%ADa-amo/",
    "featured": false
  },
  {
    "id": "CLH-065",
    "name": "Maria Pia Olivera",
    "country": "Uruguay",
    "university": "ORT Uruguay",
    "area": "Relaciones Internacionales",
    "role": "Comunidad y Talento | Relaciones Internacionales",
    "slug": "maria-pia-olivera",
    "image": "/images/members/maria-pia-olivera.webp",
    "linkedIn": "https://www.linkedin.com/in/mariapiaoliveracoccaro",
    "featured": false
  },
  {
    "id": "CLH-035",
    "name": "Maria Victoria Llorach",
    "country": "Panamá",
    "university": "ADEN Univerisity",
    "area": "Marketing",
    "role": "Marketing",
    "slug": "maria-victoria-llorach",
    "image": null,
    "linkedIn": null,
    "featured": false
  },
  {
    "id": "CLH-066",
    "name": "Martina Leicht",
    "country": "Uruguay",
    "university": "Universidad de Montevideo",
    "area": "Comunicación estratégica/Marketing",
    "role": "Comunidad y Talento",
    "slug": "martina-leich",
    "image": "/images/members/martina-leich.webp",
    "linkedIn": "https://www.linkedin.com/in/martina-leicht-05b44b340/",
    "featured": false
  },
  {
    "id": "CLH-039",
    "name": "Miguel Ángel",
    "country": "Panamá",
    "university": "Universidad Interamericana de Panamá",
    "area": "Tecnología",
    "role": "Marketing",
    "slug": "miguel-angel",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/miguel-mes-81458a285/",
    "featured": false
  },
  {
    "id": "CLH-031",
    "name": "Milton Gorocica Rivas",
    "country": "México",
    "university": "Anahuac Mayab",
    "area": "Hospitalidad-Comercio",
    "role": "Eventos y Experiencias",
    "slug": "milton-gorocica-rivas",
    "image": "/images/members/milton-gorocica-rivas.webp",
    "linkedIn": "https://www.linkedin.com/in/milton-gorocica-rivas-7a110a2b1/",
    "featured": false,
    "video": "/videos/milton-gorocica-rivas.mp4"
  },
  {
    "id": "CLH-019",
    "name": "Minerva Capcha",
    "country": "Perú",
    "university": "Universidad del Pacifíco",
    "area": "Derecho",
    "role": "Relaciones Internacionales | Eventos y Experiencias",
    "slug": "minerva-capcha",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/capcha-minerva/",
    "featured": false
  },
  {
    "id": "CLH-044",
    "name": "Nicole Ramírez",
    "country": "Ecuador",
    "university": "UEES",
    "area": "Expansión",
    "role": "Relaciones Internacionales",
    "slug": "nicole-ramirez",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/nicole-ram%C3%ADrez-chica-4573bb305/",
    "featured": false
  },
  {
    "id": "CLH-030",
    "name": "Óscar José Pleités Lemus",
    "country": "El Salvador",
    "university": "ESEN",
    "area": "Tecnología",
    "role": "BEWAY Tecnología",
    "slug": "oscar-jose-pleites",
    "image": "/images/members/oscar-jose-pleites.webp",
    "video": "/videos/oscar-jose-pleites.mp4",
    "linkedIn": "https://www.linkedin.com/in/osplei/",
    "featured": false
  },
  {
    "id": "CLH-047",
    "name": "Priscila Bryan Serrano",
    "country": "Panamá",
    "university": "Florida State University",
    "area": "Marketing",
    "role": "Marketing",
    "slug": "priscila-bryan-serrano",
    "image": "/images/members/priscila-bryan-serrano.webp",
    "video": "/videos/priscila-bryan-serrano.mp4",
    "linkedIn": "https://www.linkedin.com/in/priscilla-bryan-serrano-65b022313/",
    "featured": false
  },
  {
    "id": "CLH-050",
    "name": "Ricardo Corao",
    "country": "Panamá",
    "university": "USMA",
    "area": "Ingenieria Industrial",
    "role": "Operaciones y Eficiencia",
    "slug": "ricardo-corao",
    "image": "/images/members/ricardo-corao.webp",
    "video": "/videos/ricardo-corao.mp4",
    "linkedIn": "https://www.linkedin.com/in/ricardo-corao-837036331/",
    "featured": false
  },
  {
    "id": "CLH-037",
    "name": "Sebastián Eduardo Rotter Rochin",
    "country": "México",
    "university": "Anahuac Mayab",
    "area": "Negocios Internacionales",
    "role": "Eventos y Experiencias | Finanzas",
    "slug": "sebastian-rotter-rochin",
    "image": "/images/members/sebastian-rotter-rochin.webp",
    "video": "/videos/sebastian-rotter-rochin.mp4",
    "linkedIn": "https://www.linkedin.com/in/sebasti%C3%A1n-rotter-rochin-7ba892256/",
    "featured": false
  },
  {
    "id": "CLH-054",
    "name": "Sebastián Vigueras Araya",
    "country": "Chile",
    "university": "Pontificia Universidad Católica de Chile",
    "area": "Biomedicina",
    "role": "Comunidad y Talento | Eventos y Experiencias",
    "slug": "sebastian-vigueras-araya",
    "image": "/images/members/sebastian-vigueras-araya.webp",
    "video": "/videos/sebastian-vigueras-araya.mp4",
    "linkedIn": "https://www.linkedin.com/in/sebasti%C3%A1n-vigueras-araya-6680b9295/",
    "featured": false
  },
  {
    "id": "CLH-052",
    "name": "Simón Ospina Lizcano",
    "country": "Colombia",
    "university": "Universidad del Rosario",
    "area": "Derecho",
    "role": "Jurídico | Marketing",
    "slug": "simon-ospina-lizcano",
    "image": "/images/members/simon-ospina-lizcano.webp",
    "video": "/videos/simon-ospina-lizcano.mp4",
    "linkedIn": "https://www.linkedin.com/in/sim%C3%B3n-ospina-lizcano-200910233/",
    "featured": false
  },
  {
    "id": "CLH-057",
    "name": "Sthefan Borace",
    "country": "Panamá",
    "university": "ADEN",
    "area": "Marketing",
    "role": "Marketing",
    "slug": "sthefan-borace",
    "image": "/images/members/sthefan-borace.webp",
    "video": "/videos/sthefan-borace.mp4",
    "linkedIn": "https://www.linkedin.com/in/sthefanborace/",
    "featured": false
  },
  {
    "id": "CLH-058",
    "name": "Valeria Espinoza León",
    "country": "Ecuador",
    "university": "UEES/Universidad de Especialidades Espíritu Santo",
    "area": "Gestión de proyectos y Cadena de Suministro",
    "role": "Eventos y Experiencias | Tecnología",
    "slug": "valeria-espinoza-leon",
    "image": "/images/members/valeria-espinoza-leon.webp",
    "linkedIn": "https://www.linkedin.com/in/valeria-espinoza-le%C3%B3n-4bb325306/",
    "featured": false,
    "video": "/videos/valeria-espinoza-leon.mp4"
  },
  {
    "id": "CLH-038",
    "name": "Valeria Riojas Dávila",
    "country": "México",
    "university": "Anahuac Mayab",
    "area": "Mercadotecnia",
    "role": "Eventos y Experiencias",
    "slug": "valeria-riojas-davila",
    "image": "/images/members/valeria-riojas-davila.webp",
    "video": "/videos/valeria-riojas-davila.mp4",
    "linkedIn": "https://www.linkedin.com/in/valeria-riojas-d/",
    "featured": false
  },
  {
    "id": "CLH-060",
    "name": "Vivianna Reynold",
    "country": "México",
    "university": "Tecnológico de Monterrey",
    "area": "Marketing",
    "role": "Marketing",
    "slug": "vivianna-reynold",
    "image": "/images/members/vivianna-reynold.webp",
    "video": "/videos/vivianna-reynold.mp4",
    "linkedIn": "www.linkedin.com/in/vivianna-reynold-8120b1300",
    "featured": false
  },
  {
    "id": "CLH-063",
    "name": "Yamel Fernandez",
    "country": "República Dominicana",
    "university": "Universidad Iberoamericana (UNIBE)",
    "area": "Fotografía",
    "role": "Marketing",
    "slug": "yamel-fernandez",
    "image": "/images/members/yamel-fernandez.webp",
    "video": "/videos/yamel-fernandez.mp4",
    "linkedIn": "https://linkedin.com/in/yamel-fernández-899617317/?skipRedirect=true",
    "featured": false
  },
  {
    "id": "CLH-003",
    "name": "Anahí Ayala Monzón",
    "country": "Paraguay",
    "university": "Universidad Católica \"Nuestra Señora de la Asunción\"",
    "area": "Relaciones Internacionales",
    "role": "Miembro",
    "slug": "anahi-ayala-monzon",
    "image": "/images/members/anahi-ayala-monzon.webp",
    "linkedIn": "https://www.linkedin.com/in/anahiayalazn/?locale=en",
    "featured": false
  },
  {
    "id": "CLH-070",
    "name": "Ander García",
    "country": "México",
    "university": "Universidad Panamericana",
    "area": "Derecho",
    "role": "Miembro",
    "slug": "ander-garcia",
    "image": "/images/members/ander-garcia.webp",
    "linkedIn": null,
    "featured": false
  },
  {
    "id": "CLH-014",
    "name": "Federico Lander",
    "country": "Venezuela",
    "university": "Anahuac Puebla",
    "area": "Ingeniería en Negocios",
    "role": "Miembro",
    "slug": "federico-lander",
    "image": "/images/members/federico-lander.webp",
    "video": "/videos/federico-lander.mp4",
    "linkedIn": "https://linkedin.com/in/federicolander29/es/?skipRedirect=true",
    "featured": false
  },
  {
    "id": "CLH-051",
    "name": "Fran Rodgmont",
    "country": "El Salvador",
    "university": "Universidad Don Bosco",
    "area": "Ingeniería Informática",
    "role": "Miembro",
    "slug": "fran-rodgmont",
    "image": "/images/members/fran-rodgmont.webp",
    "linkedIn": "https://linkedin.com/in/rodgmont/?skipRedirect=true",
    "featured": false
  },
  {
    "id": "CLH-061",
    "name": "Gilberto Ceballos Ponce de León",
    "country": "México",
    "university": "Universidad Panamericana",
    "area": "Derecho Corporativo",
    "role": "Miembro",
    "slug": "gilberto-ceballos",
    "image": "/images/members/gilberto-ceballos.webp",
    "video": "/videos/gilberto-ceballos.mp4",
    "linkedIn": "https://www.linkedin.com/in/gilberto-ceballos-97aa94230/",
    "featured": false
  },
  {
    "id": "CLH-073",
    "name": "Iker Gutiérrez de Jesús",
    "country": "México",
    "university": "Tecnológico de Monterrey",
    "area": "Ingeniería Industrial",
    "role": "Miembro",
    "slug": "iker-guitierrez-de-jesus",
    "image": "/images/members/iker-guitierrez-de-jesus.webp",
    "linkedIn": "https://www.linkedin.com/in/iker-guti%C3%A9rrez-de-jes%C3%BAs-aa7b05244/",
    "featured": false,
    "video": "/videos/iker-guitierrez-de-jesus.mp4"
  },
  {
    "id": "CLH-023",
    "name": "Ivo Gómez De Segura",
    "country": "España",
    "university": "IE",
    "area": "Relaciones Internacionales",
    "role": "Miembro",
    "slug": "ivo-gomez-de-segura",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/ivogomezdeseguragomez/?locale=es",
    "featured": false
  },
  {
    "id": "CLH-024",
    "name": "Jorge Andrés Calderón",
    "country": "Ecuador",
    "university": "Universidad San Francisco de Quito",
    "area": "Economía",
    "role": "Miembro",
    "slug": "jorge-calderon",
    "image": "/images/members/jorge-calderon.webp",
    "video": "/videos/jorge-calderon.mp4",
    "linkedIn": "www.linkedin.com/in/jorgeandrscalderon",
    "featured": false
  },
  {
    "id": "CLH-012",
    "name": "Karen Jimena Fonseca",
    "country": "Colombia",
    "university": "Universidad Externado de Colombia",
    "area": "Finanzas",
    "role": "Miembro",
    "slug": "karen-jimena-fonseca",
    "image": "/images/members/karen-jimena-fonseca.webp",
    "video": "/videos/karen-jimena-fonseca.mp4",
    "linkedIn": "https://www.linkedin.com/in/karen-jimena-fonseca/",
    "featured": false
  },
  {
    "id": "CLH-077",
    "name": "Krissia Alejandra Bueno",
    "country": "",
    "university": "",
    "area": "",
    "role": "Miembro",
    "slug": "krissia-alejandra-bueno-clh-077",
    "image": null,
    "linkedIn": null,
    "featured": false
  },
  {
    "id": "CLH-071",
    "name": "Laura Nayeli Mendez Martinez",
    "country": "México",
    "university": "Tecnológico de Monterrey",
    "area": "Negocios Internacionales",
    "role": "Miembro",
    "slug": "laura-nayeli-mendez-martinez",
    "image": "/images/members/laura-nayeli-mendez-martinez.webp",
    "video": "/videos/laura-nayeli-mendez-martinez.mp4",
    "linkedIn": "https://www.linkedin.com/in/laura-nayeli-mendez-martinez-979627381/",
    "featured": false
  },
  {
    "id": "CLH-072",
    "name": "Luz Aiyana González Gordillo",
    "country": "México",
    "university": "Anáhuac Puebla",
    "area": "Turismo Internacional",
    "role": "Miembro",
    "slug": "luz-aiyana-gonzalez-gordillo",
    "image": "/images/members/luz-aiyana-gonzalez-gordillo.webp",
    "linkedIn": "https://www.linkedin.com/in/aiyana-gonz%C3%A1lez?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    "featured": false,
    "video": "/videos/luz-aiyana-gonzalez-gordillo.mp4"
  },
  {
    "id": "CLH-074",
    "name": "Maria Jose Merida Acuña",
    "country": "México",
    "university": "Anáhuac Mayab",
    "area": "Relaciones Internacionales",
    "role": "Miembro",
    "slug": "maria-jose-merida-acuna",
    "image": "/images/members/maria-jose-merida-acuna.webp",
    "video": "/videos/maria-jose-merida-acuna.mp4",
    "linkedIn": "https://www.linkedin.com/in/maria-jose-merida-acu%C3%B1a-a6b0802ba/",
    "featured": false
  },
  {
    "id": "CLH-027",
    "name": "Maria Lucia Massé Porras",
    "country": "Colombia",
    "university": "Universidad Externado de Colombia",
    "area": "Finanzas",
    "role": "Miembro",
    "slug": "maria-lucia-masse-porras",
    "image": "/images/members/maria-lucia-masse-porras.webp",
    "linkedIn": "https://www.linkedin.com/in/mariamasse/",
    "featured": false
  },
  {
    "id": "CLH-021",
    "name": "Mauricio Rodriguez Limón",
    "country": "México",
    "university": "Anahuac Mayab",
    "area": "Negocios",
    "role": "Miembro",
    "slug": "mauricio-rodriguez-limon",
    "image": "/images/members/mauricio-rodriguez-limon.webp",
    "linkedIn": "https://www.linkedin.com/in/mauricio-rodr%C3%ADguez-lim%C3%B3n-8651a9306/",
    "featured": false
  },
  {
    "id": "CLH-048",
    "name": "Miguel José Taveras",
    "country": "República Dominicana",
    "university": "PUCMM",
    "area": "Derecho",
    "role": "Miembro",
    "slug": "miguel-jose-taveras",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/miguel-jos%C3%A9-taveras-ben%C3%ADtez-88b9a52a1/",
    "featured": false
  },
  {
    "id": "CLH-045",
    "name": "Milla (Allegra) Balandrán",
    "country": "México",
    "university": "Tec. De Monterrey",
    "area": "Relaciones Internacionales",
    "role": "Miembro",
    "slug": "milla-allegra-balandran",
    "image": "/images/members/milla-allegra-balandran.webp",
    "linkedIn": "https://www.linkedin.com/in/millaallegraa/",
    "featured": false,
    "video": "/videos/milla-allegra-balandran.mp4"
  },
  {
    "id": "CLH-036",
    "name": "Raphael Andersor Sánchez Pinto",
    "country": "Perú",
    "university": "Universidad del Pacifíco",
    "area": "Finanzas",
    "role": "Miembro",
    "slug": "raphael-andersor-sanchez-pinto",
    "image": "/images/members/raphael-andersor-sanchez-pinto.webp",
    "video": "/videos/raphael-andersor-sanchez-pinto.mp4",
    "linkedIn": "https://www.linkedin.com/in/raphael-sanchez-pinto",
    "featured": false
  },
  {
    "id": "CLH-078",
    "name": "Roberto Morán",
    "country": "",
    "university": "",
    "area": "",
    "role": "Miembro",
    "slug": "roberto-moran",
    "image": null,
    "linkedIn": null,
    "featured": false
  },
  {
    "id": "CLH-046",
    "name": "Rodrigo Alejandro Lopez Bolaños",
    "country": "El Salvador",
    "university": "ESEN",
    "area": "Estrategia e Innovación",
    "role": "Miembro",
    "slug": "rodrigo-lopez-bolanos",
    "image": "/images/members/rodrigo-lopez-bolanos.webp",
    "video": "/videos/rodrigo-lopez-bolanos.mp4",
    "linkedIn": "https://www.linkedin.com/in/rodrigo-l%C3%B3pez-161954250/",
    "featured": false
  },
  {
    "id": "CLH-049",
    "name": "Sophia de Leone",
    "country": "Argentina",
    "university": "Universidad de San Andrés",
    "area": "Negocios Digitales",
    "role": "Miembro",
    "slug": "sophia-de-leone",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/sophia-de-leone/",
    "featured": false
  },
  {
    "id": "CLH-056",
    "name": "Stephany Cajamarca",
    "country": "Ecuador",
    "university": "UEES",
    "area": "Negocios Internacionales",
    "role": "Miembro",
    "slug": "stephany-cajamarca",
    "image": null,
    "linkedIn": "https://www.linkedin.com/in/stephany-cajamarca-7548ab3b0/",
    "featured": false
  },
  {
    "id": "CLH-069",
    "name": "Valeria Aspiazu",
    "country": "Ecuador",
    "university": "Universidad Internacional de la Rioja",
    "area": "Educación",
    "role": "Miembro",
    "slug": "valeria-aspiazu",
    "image": "/images/members/valeria-aspiazu.webp",
    "linkedIn": "https://www.linkedin.com/in/valeria-aspiazu-51145221a/",
    "featured": false
  },
  {
    "id": "CLH-059",
    "name": "Valeria Ocheita",
    "country": "Guatemala",
    "university": "Universidad del Valle",
    "area": "Comunicación estratégica",
    "role": "Miembro",
    "slug": "valeria-ocheita",
    "image": "/images/members/valeria-ocheita.webp",
    "linkedIn": "https://www.linkedin.com/in/valeria-ocheita-95931a380/",
    "featured": false
  },
  {
    "id": "CLH-064",
    "name": "Yarey Cristina Coronel Rojas",
    "country": "Ecuador",
    "university": "UEES",
    "area": "Eventos y Experiencias",
    "role": "Miembro",
    "slug": "yarey-coronel",
    "image": "/images/members/yarey-coronel.webp",
    "video": "/videos/yarey-coronel.mp4",
    "linkedIn": "https://www.linkedin.com/in/yarey-coronel-88217834a/",
    "featured": false
  }
];
